### ISSUE TITLE
TorchMetrics incorrect Error about devices

### ISSUE THREAD

**Issue by cemde** [PyTorchLightning/metrics#206] opened 2021-04-27 16:56 UTC
## 🐛 Bug

I was going to use `torchmetrics.Accuracy` for multi-label classification. 
Under certain conditions the torchmetrics.Accuracy module breaks by complaining predictions and targets would be on different devices, despite them being on the same device.

``` python
import torch
from torchmetrics import Accuracy
a = Accuracy()
t = torch.tensor([1,1,0]).to('cuda:2').to(torch.int64)
p = torch.tensor([0.1,0.5,0.2]).to('cuda:2').to(torch.float32)
```

We can test that these objects are indeed on the same device:

``` python
>>> t.dtype
torch.int64
>>> p.dtype
torch.float32
>>> t.device
device(type='cuda', index=2)
>>> p.device
device(type='cuda', index=2)
```
Running
```python
a(p,t)
```
 results in this error
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/users-1/anaconda3/envs/E1/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/users-1/anaconda3/envs/E1/lib/python3.8/site-packages/torchmetrics/metric.py", line 152, in forward
    self.update(*args, **kwargs)
  File "/users-1/anaconda3/envs/E1/lib/python3.8/site-packages/torchmetrics/metric.py", line 199, in wrapped_func
    return update(*args, **kwargs)
  File "/users-1/anaconda3/envs/E1/lib/python3.8/site-packages/torchmetrics/classification/accuracy.py", line 142, in update
    self.correct += correct
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:2 and cpu!
```

### To Reproduce

run the code above

#### Code sample

see above

### Expected behavior

calculate the accuracy properly

### Environment

CUDA: 10.2
Python 3.8.8
Torch: 1.8.1
Torchmetrics: 0.2.0 (pyhd8ed1ab_0    conda-forge)
Pytorch-lightning: 1.2.6

**Comment by maximsch2** [comment] 2021-04-27 17:08
You should move the metric to the same device as well, can you try running `a.to('cuda:2')`?

**Comment by cemde** [comment] 2021-04-27 18:36
> You should move the metric to the same device as well, can you try running `a.to('cuda:2')`?

thanks for the reply. I initialise the `Accuracy` in the init method of a pytorch-lightning module using `nn.ModuleList`. During `init` the `self.device` attribute is still `cpu`. Further, I thought that pl would automatically push my metrics to the GPU when using `ModuleList`. 

``` python
class MyNet(pl.LightningModule):
    def __init__(self, cfg):
        super(MyNet, self).__init__()
        self.configure_metrics()
        ...
        ...

    def configure_metrics(self):
        splits = ["train", "val", "test"]
        accuracy_list = nn.ModuleList([Accuracy() for _ in splits])
        f1_list = nn.ModuleList([F1(num_classes=self.cfg.DATA.NUM_CLASSES) for _ in splits])

        self.metrics_dict = {split : {} for split in splits}
        for split, acc, f1 in zip(splits, accuracy_list, f1_list):
            self.metrics_dict[split] = {'accuracy': acc, 'f1' : f1}
```

**Comment by maximsch2** [comment] 2021-04-27 20:10
If you want to get the thing moved to the device in your metrics_dict you should at least use `nn.ModuleDict` - that way PyTorch will take care of the move. I think you might have a hack trying to get it moved due to accuracy_list, but that's not even on `self`, so is not persisted.

Additionally, check out `MetricsCollection` - it will require you flipping the pattern a bit, but doing something like this will make sense:
```python
metrics = MetricCollection({"accuracy": acc, "f1": f1})
self.train_metrics = metrics.clone(prefix="train_")
self.val_metrics = metrics.clone(prefix="val_")
```

**Comment by SkafteNicki** [comment] 2021-04-27 20:31
Agree with @maximsch2, the problem is that pytorch is not correctly registering your metrics as submodules of your model.
Please check the `model.children()` method, if the metrics are not listed then they will not be moved to the correct device.
Also stated in the documentation: https://torchmetrics.readthedocs.io/en/latest/pages/overview.html#metrics-and-devices
A simple fix for your use case @cemde should be 
```python
class MyNet(pl.LightningModule):
    def __init__(self, cfg):
        super(MyNet, self).__init__()
        self.configure_metrics()
        ...
        ...

    def configure_metrics(self):
        splits = ["Train", "val", "test"] # note that we cannot have the split be name train/training as these are protected attributes in pytorch
        accuracy_list = nn.ModuleList([Accuracy() for _ in splits])
        f1_list = nn.ModuleList([F1(num_classes=self.cfg.DATA.NUM_CLASSES) for _ in splits])

        self.metrics_dict = nn.ModuleDict({split : nn.ModuleDict() for split in splits}
        for split, acc, f1 in zip(splits, accuracy_list, f1_list):
            self.metrics_dict[split].update({'accuracy': acc, 'f1' : f1})
```

**Comment by cemde** [comment] 2021-04-27 22:35
I figured it out: Using `ModuleDict` in combination with `train` as split does not work as it is registered already. But using `MetricCollection` works fine. I hope it properly distinguishes between Multi-label and Multi-class automatically.

**Comment by SkafteNicki** [comment] 2021-04-28 08:44
`MetricCollection` is just redirecting all arguments passed in to the individual metrics in the collection, so if they correctly distinguishes between multi-label and multi-class the collection should also do it.
Closing the issue. Please re-open if more questions arise.

**Closed by SkafteNicki** 2021-04-28 08:44 UTC
Labels: bug / fix, help wanted
