### ISSUE TITLE
Unhashable type list in validation loop

### ISSUE THREAD

**Issue by Ierezell** [PyTorchLightning/metrics#488] opened 2021-08-31 20:29 UTC
## 🐛 Bug

When having metrics bleu and wer as instances in class, validation loop raise the following error : 
<details>
<summary>Traceback</summary>
<br>

```sh
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /mnt/Projets/nlp/libs/nlp/spellcheckers/deep_checker.py:350 in launch_train                      │
│                                                                                                  │
│   347 │   │   logger.info("Training started")                                                    │
│   348 │   │   logger.info(f"Training with {args}")                                               │
│   349 │   │   trainer.tune(model=module, datamodule=data_module)                                 │
│ ❱ 350 │   │   trainer.fit(model=module, datamodule=data_module)                                  │
│   351                                                                                            │
│   352                                                                                            │
│   353 if __name__ == "__main__":                                                                 │
│                                                                                                  │
│ /mnt/Projets/nlp/.venv/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py:553 in   │
│ fit                                                                                              │
│                                                                                                  │
│    550 │   │                                                                                     │
│    551 │   │   self.checkpoint_connector.resume_start()                                          │
│    552 │   │                                                                                     │
│ ❱  553 │   │   self._run(model)                                                                  │
│    554 │   │                                                                                     │
│    555 │   │   assert self.state.stopped                                                         │
│    556 │   │   self.training = False                                                             │
│                                                                                                  │
│ /mnt/Projets/nlp/.venv/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py:918 in   │
│ _run                                                                                             │
│                                                                                                  │
│    915 │   │   self.checkpoint_connector.restore_training_state()                                │
│    916 │   │                                                                                     │
│    917 │   │   # dispatch `start_training` or `start_evaluating` or `start_predicting`           │
│ ❱  918 │   │   self._dispatch()                                                                  │
│    919 │   │                                                                                     │
│    920 │   │   # plugin will finalized fitting (e.g. ddp_spawn will load trained model)          │
│    921 │   │   self._post_dispatch()                                                             │
│                                                                                                  │
│ /mnt/Projets/nlp/.venv/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py:986 in   │
│ _dispatch                                                                                        │
│                                                                                                  │
│    983 │   │   elif self.predicting:                                                             │
│    984 │   │   │   self.accelerator.start_predicting(self)                                       │
│    985 │   │   else:                                                                             │
│ ❱  986 │   │   │   self.accelerator.start_training(self)                                         │
│    987 │                                                                                         │
│    988 │   def run_stage(self):                                                                  │
│    989 │   │   self.accelerator.dispatch(self)                                                   │
│                                                                                                  │
│ /mnt/Projets/nlp/.venv/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py │
│ :92 in start_training                                                                            │
│                                                                                                  │
│    89 │   │   self.setup_precision_plugin()                                                      │
│    90 │                                                                                          │
│    91 │   def start_training(self, trainer: "pl.Trainer") -> None:                               │
│ ❱  92 │   │   self.training_type_plugin.start_training(trainer)                                  │
│    93 │                                                                                          │
│    94 │   def start_evaluating(self, trainer: "pl.Trainer") -> None:                             │
│    95 │   │   self.training_type_plugin.start_evaluating(trainer)                                │
│                                                                                                  │
│ /mnt/Projets/nlp/.venv/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/train │
│ ing_type_plugin.py:161 in start_training                                                         │
│                                                                                                  │
│   158 │                                                                                          │
│   159 │   def start_training(self, trainer: "pl.Trainer") -> None:                               │
│   160 │   │   # double dispatch to initiate the training loop                                    │
│ ❱ 161 │   │   self._results = trainer.run_stage()                                                │
│   162 │                                                                                          │
│   163 │   def start_evaluating(self, trainer: "pl.Trainer") -> None:                             │
│   164 │   │   # double dispatch to initiate the test loop                                        │
│                                                                                                  │
│ /mnt/Projets/nlp/.venv/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py:996 in   │
│ run_stage                                                                                        │
│                                                                                                  │
│    993 │   │   │   return self._run_evaluate()                                                   │
│    994 │   │   if self.predicting:                                                               │
│    995 │   │   │   return self._run_predict()                                                    │
│ ❱  996 │   │   return self._run_train()                                                          │
│    997 │                                                                                         │
│    998 │   def _pre_training_routine(self):                                                      │
│    999 │   │   # wait for all to join if on distributed                                          │
│                                                                                                  │
│ /mnt/Projets/nlp/.venv/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py:1031 in  │
│ _run_train                                                                                       │
│                                                                                                  │
│   1028 │   │   if not self.is_global_zero and self.progress_bar_callback is not None:            │
│   1029 │   │   │   self.progress_bar_callback.disable()                                          │
│   1030 │   │                                                                                     │
│ ❱ 1031 │   │   self._run_sanity_check(self.lightning_module)                                     │
│   1032 │   │                                                                                     │
│   1033 │   │   # enable train mode                                                               │
│   1034 │   │   self.model.train()                                                                │
│                                                                                                  │
│ /mnt/Projets/nlp/.venv/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py:1115 in  │
│ _run_sanity_check                                                                                │
│                                                                                                  │
│   1112 │   │   │                                                                                 │
│   1113 │   │   │   # run eval step                                                               │
│   1114 │   │   │   with torch.no_grad():                                                         │
│ ❱ 1115 │   │   │   │   self._evaluation_loop.run()                                               │
│   1116 │   │   │                                                                                 │
│   1117 │   │   │   self.on_sanity_check_end()                                                    │
│   1118                                                                                           │
│                                                                                                  │
│ /mnt/Projets/nlp/.venv/lib/python3.9/site-packages/pytorch_lightning/loops/base.py:118 in run    │
│                                                                                                  │
│   115 │   │   │   except StopIteration:                                                          │
│   116 │   │   │   │   break                                                                      │
│   117 │   │                                                                                      │
│ ❱ 118 │   │   output = self.on_run_end()                                                         │
│   119 │   │   return output                                                                      │
│   120 │                                                                                          │
│   121 │   @abstractmethod                                                                        │
│                                                                                                  │
│ /mnt/Projets/nlp/.venv/lib/python3.9/site-packages/pytorch_lightning/loops/dataloader/evaluation │
│ _loop.py:149 in on_run_end                                                                       │
│                                                                                                  │
│   146 │   │   self.epoch_loop.predictions.to_disk()                                              │
│   147 │   │                                                                                      │
│   148 │   │   # enable train mode again                                                          │
│ ❱ 149 │   │   self.on_evaluation_model_train()                                                   │
│   150 │   │                                                                                      │
│   151 │   │   return eval_loop_results                                                           │
│   152                                                                                            │
│                                                                                                  │
│ /mnt/Projets/nlp/.venv/lib/python3.9/site-packages/pytorch_lightning/loops/dataloader/evaluation │
│ _loop.py:201 in on_evaluation_model_train                                                        │
│                                                                                                  │
│   198 │   │   if self.trainer.testing:                                                           │
│   199 │   │   │   model_ref.on_test_model_train()                                                │
│   200 │   │   else:                                                                              │
│ ❱ 201 │   │   │   model_ref.on_validation_model_train()                                          │
│   202 │                                                                                          │
│   203 │   def on_evaluation_end(self, *args: Any, **kwargs: Any) -> None:                        │
│   204 │   │   """Runs ``on_{validation/test}_end`` hook"""                                       │
│                                                                                                  │
│ /mnt/Projets/nlp/.venv/lib/python3.9/site-packages/pytorch_lightning/core/hooks.py:202 in        │
│ on_validation_model_train                                                                        │
│                                                                                                  │
│   199 │   │   """                                                                                │
│   200 │   │   Sets the model to train during the val loop                                        │
│   201 │   │   """                                                                                │
│ ❱ 202 │   │   self.trainer.model.train()                                                         │
│   203 │                                                                                          │
│   204 │   def on_test_model_train(self) -> None:                                                 │
│   205 │   │   """                                                                                │
│                                                                                                  │
│ /mnt/Projets/nlp/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py:1448 in train      │
│                                                                                                  │
│   1445 │   │   │   Module: self                                                                  │
│   1446 │   │   """                                                                               │
│   1447 │   │   self.training = mode                                                              │
│ ❱ 1448 │   │   for module in self.children():                                                    │
│   1449 │   │   │   module.train(mode)                                                            │
│   1450 │   │   return self                                                                       │
│   1451                                                                                           │
│                                                                                                  │
│ /mnt/Projets/nlp/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py:1344 in children   │
│                                                                                                  │
│   1341 │   │   Yields:                                                                           │
│   1342 │   │   │   Module: a child module                                                        │
│   1343 │   │   """                                                                               │
│ ❱ 1344 │   │   for name, module in self.named_children():                                        │
│   1345 │   │   │   yield module                                                                  │
│   1346 │                                                                                         │
│   1347 │   def named_children(self) -> Iterator[Tuple[str, 'Module']]:                           │
│                                                                                                  │
│ /mnt/Projets/nlp/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py:1363 in            │
│ named_children                                                                                   │
│                                                                                                  │
│   1360 │   │   """                                                                               │
│   1361 │   │   memo = set()                                                                      │
│   1362 │   │   for name, module in self._modules.items():                                        │
│ ❱ 1363 │   │   │   if module is not None and module not in memo:                                 │
│   1364 │   │   │   │   memo.add(module)                                                          │
│   1365 │   │   │   │   yield name, module                                                        │
│   1366                                                                                           │
│                                                                                                  │
│ /mnt/Projets/nlp/.venv/lib/python3.9/site-packages/torchmetrics/metric.py:516 in __hash__        │
│                                                                                                  │
│   513 │   │   │   else:                                                                          │
│   514 │   │   │   │   hash_vals.append(val)                                                      │
│   515 │   │                                                                                      │
│ ❱ 516 │   │   return hash(tuple(hash_vals))                                                      │
│   517 │                                                                                          │
│   518 │   def __add__(self, other: "Metric") -> "Metric":                                        │
│   519 │   │   return CompositionalMetric(torch.add, self, other)                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: unhashable type: 'list'

```

</details>

#### Code sample
In the `__init__` method

```python
self.train_bleu = torchmetrics.BLEUScore()
self.valid_bleu = torchmetrics.BLEUScore()

self.train_wer = torchmetrics.WER()
self.valid_wer = torchmetrics.WER()
```

Commenting those let the validation loop run correctly. With it the TypeError is raised. 
### Expected behavior

Being able to log bleu and were metrics in the validation loop. 

### Environment

- PyTorch Version (e.g., 1.0): 1.8.1
- OS (e.g., Linux): Archlinux 5.13.12
- How you installed PyTorch (`conda`, `pip`, source): poetry (pip + venv)
- Build command you used (if compiling from source):
- Python version: 3.9.6
- CUDA/cuDNN version: Cuda 11.4 Nvidia 470.63.01
- GPU models and configuration: GTX1650 Ti MaxQ
- Any other relevant information:

**Comment by SkafteNicki** [comment] 2021-09-01 15:06
Could reproduce the issue for WER but not BLEUScore with v0.5.0 of torchmetrics. However, running master everything seems fine. There, Please upgrade to master:
```bash
pip install git+https://github.com/PytorchLightning/metrics.git@master
```
and the issue should disappear.

**Comment by Ierezell** [comment] 2021-09-01 15:13
Hi @SkafteNicki, 
Maybe I found the error: the metric is unable to process empty lists (which didn't know I could get during training). 

My Translation model is calling a beam search and I just discovered that it can generate nothing.... which makes the metric crash. 

The first epochs were fine as they generate random gibberish but then, the model would output empty lists which make the metric crash.

Epoch 1 : generate => [["crap", "crappy"]]    => Fine
..........few epochs.......   
Epoch 3 : generate => [ [], [] ]  => crash

I added on my side a check like `[sentence.split() or [""] for sentence in generated_sentences ]` and the error disappeared. 

Would it be a nice feature for the metric to be able to return a 0 score on an empty list? 

If you don't plan to support an empty list then I guess it's resolved and we can close, else we can discuss the fix.

Have a great day

**Comment by SkafteNicki** [comment] 2021-09-02 07:16
Yes, I also came to the conclusion that was the problem.
Have you tried installing the master version of torchmetrics as I wrote in my previous message?

**Comment by karthikrangasai** [comment] 2021-09-02 09:29
Hello @Ierezell ,
We support Corpus BLEU like function from the nltk package.

Hence, for empty sentences the metric will try to iterate through an empty string because you will be passing a `Sequence[str]` to the metric as predictions.

```
 tgt_lns = tokenize_labels(batch["labels"])
pred_lns = generate(batch["input_ids"], batch["attention_mask"])
# wrap targets in list as score expects a list of potential references
tgt_tokens = tuple([tuple([tuple(reference.split()) for reference in tgt_lns])]) # Sequence[Sequence[Sequence[str]]]
pred_tokens = tuple([tuple(prediction.split()) for prediction in pred_lns]) # Sequence[Sequence[str]]
result = self.bleu(tgt_tokens, pred_tokens)
```

Something like this should help as it wraps the inputs to a corpus bleu like input.

**Comment by Borda** [comment] 2021-09-02 12:25
@stancld mind help here? :]

**Comment by Ierezell** [comment] 2021-09-02 13:47
Hi @SkafteNicki, I will be trying that to see if anything changes thanks for the support! 

@karthikrangasai I have indeed done that (something similar) as I have seen that this metric needed lists. 
However, some of the `pred_lns` were empty which led to having `prediction.split()` as an empty list thus the `split() or [""]` which is hackish but fixed it. 

I will try the master version and update you. 

Thanks a lot for your support.

**Comment by stancld** [comment] 2021-09-02 17:14
@Borda  Yes, I'll be happy to take a look :)

**Comment by SkafteNicki** [comment] 2021-09-02 17:24
I created PR #496 that adds hashing of all metrics.
As I already commented I am pretty sure the issue is already fixed on master due to the recent refactors of the text metrics, but if the tests in the PR passes then it is definitely solved.

**Comment by SkafteNicki** [comment] 2021-09-03 07:19
Okay PR #496 passed without problems, so closing the issue.

**Closed by SkafteNicki** 2021-09-03 07:19 UTC
Labels: bug / fix, help wanted
