### ISSUE TITLE
ConfusionMatrix and MatthewsCorrCoef in a MetricCollection throw an Exception

### ISSUE THREAD

**Issue by maestro4** [PyTorchLightning/metrics#1050] opened 2022-05-26 14:27 UTC
## 🐛 Bug

Following works:
```python
import torchmetrics
import torch
target = torch.tensor([[0, 1, 0], [1, 0, 1]])
preds = torch.tensor([[0, 0, 1], [1, 0, 1]])
confmat = torchmetrics.ConfusionMatrix(num_classes=3)
print(confmat(preds, target))

mat = torchmetrics.MatthewsCorrCoef(num_classes=3)
print(mat(preds, target))
```

But following throws an exception:
```python
import torchmetrics
import torch
target = torch.tensor([[0, 1, 0], [1, 0, 1]])
preds = torch.tensor([[0, 0, 1], [1, 0, 1]])

metrics = torchmetrics.MetricCollection([
    torchmetrics.ConfusionMatrix(num_classes=3,),
    torchmetrics.MatthewsCorrCoef(num_classes=3)
])

metrics.update(preds, target)
print(metrics.compute())
```

I believe the type of the tensor at the following line is the issue:
https://github.com/PyTorchLightning/metrics/blob/4a281494ee1113992dc69e3b471b2f3b43549929/torchmetrics/classification/matthews_corrcoef.py#L81

I'm using the version 0.8.2

**Comment by SkafteNicki** [comment] 2022-05-27 08:44
Hi @maestro4,
Thanks for reporting this issue. I could not reproduce on master and it seems to already be solve in this PR: https://github.com/PyTorchLightning/metrics/pull/1022.
Please upgrade to master or wait for release v0.9 that should be out in one of the following days.
Closing issue.

**Closed by SkafteNicki** 2022-05-27 08:44 UTC
