### ISSUE TITLE
`RetrievalPrecision` hangs in DDP mode. 

### ISSUE THREAD

**Issue by riklopfer** [PyTorchLightning/metrics#813] opened 2022-01-28 18:56 UTC
## 🐛 Bug

`RetrievalPrecision(k=1)` hangs in DDP mode. Running on a single node with multiple GPUs. 

### To Reproduce

1. Run a model which computes `RetrievalPrecision` as a validation metric in DDP mode 
2. Wait for it to hang on validation

Or

1. Run code below (successfully fails with `--gpus=0` or otherwise)
2. Observe the below error. **However** I am experiencing a hang not an error in the real code. 

```
  File "boring_model.py", line 72, in validation_epoch_end
    self.log_dict(self.val_metrics_other.compute(), prog_bar=True)
  File "/usr/local/Caskroom/miniforge/base/envs/boring-model/lib/python3.8/site-packages/torchmetrics/collections.py", line 125, in compute
    return {k: m.compute() for k, m in self.items()}
  File "/usr/local/Caskroom/miniforge/base/envs/boring-model/lib/python3.8/site-packages/torchmetrics/collections.py", line 125, in <dictcomp>
    return {k: m.compute() for k, m in self.items()}
  File "/usr/local/Caskroom/miniforge/base/envs/boring-model/lib/python3.8/site-packages/torchmetrics/metric.py", line 377, in wrapped_func
    with self.sync_context(
  File "/usr/local/Caskroom/miniforge/base/envs/boring-model/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/local/Caskroom/miniforge/base/envs/boring-model/lib/python3.8/site-packages/torchmetrics/metric.py", line 348, in sync_context
    self.sync(
  File "/usr/local/Caskroom/miniforge/base/envs/boring-model/lib/python3.8/site-packages/torchmetrics/metric.py", line 300, in sync
    self._sync_dist(dist_sync_fn, process_group=process_group)
  File "/usr/local/Caskroom/miniforge/base/envs/boring-model/lib/python3.8/site-packages/torchmetrics/metric.py", line 248, in _sync_dist
    if isinstance(output_dict[attr][0], Tensor):
IndexError: list index out of range
```

#### Code sample

The code below (which is an approximation of what I'm doing) will fail with `IndexError: list index out of range` w/o GPU. However, it will succeed with different values of `seed`. I guess that sometimes the metric will not get updated? Could this be the issue? 

```python
import argparse
import os
import random

import torch
import torch.nn.functional as F
import torchmetrics
from pytorch_lightning import LightningModule, Trainer
from pytorch_lightning.plugins import DDPPlugin
from torch.utils.data import DataLoader, Dataset


class RandomDataset(Dataset):

    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index], torch.tensor([index % 2])

    def __len__(self):
        return self.len


class BoringModel(LightningModule):

    def __init__(self, seed: int):
        super().__init__()
        self.rng = random.Random(seed)
        self.layer = torch.nn.Linear(32, 1)

        self.val_metrics = torchmetrics.MetricCollection(
            (
                torchmetrics.RetrievalPrecision(k=1),
                torchmetrics.F1Score()
            )
        )

        self.val_metrics_other = torchmetrics.MetricCollection(
            (
                torchmetrics.RetrievalPrecision(k=1),
                torchmetrics.F1Score()
            ),
            prefix="other_"
        )

    def forward(self, x):
        return torch.sigmoid(self.layer(x))

    def training_step(self, batch, batch_idx):
        data, index = batch
        res = self(data)
        loss = F.binary_cross_entropy(res, index.float())
        return loss

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)

    def validation_step(self, batch, batch_idx):
        data, index = batch
        res = self(data)
        # not all data goes to the same set of metrics. the actual logic is (obviously) more
        # involved. could this be the issue?
        if self.rng.random() < 0.2:
            self.val_metrics_other.update(res, index, indexes=index)
        else:
            self.val_metrics.update(res, index, indexes=index)

    def validation_epoch_end(self, outputs):
        self.log_dict(self.val_metrics.compute(), prog_bar=True)
        self.log_dict(self.val_metrics_other.compute(), prog_bar=True)
        self.val_metrics.reset()
        self.val_metrics_other.reset()

    def train_dataloader(self):
        return DataLoader(RandomDataset(32, 256), batch_size=2)

    def val_dataloader(self):
        return DataLoader(RandomDataset(32, 256), batch_size=2)


def run(args):
    model = BoringModel(args.seed)
    trainer = Trainer(
        default_root_dir=os.getcwd(),
        max_epochs=2,
        gpus=args.gpus,
        strategy=DDPPlugin(find_unused_parameters=False)
    )
    trainer.fit(model)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("--gpus", type=int, default=2)
    parser.add_argument("--seed", type=int, default=23239678234)

    run(parser.parse_args())
```

### Expected behavior

Compute the metric and not hang. 

### Environment

- PyTorch Version (e.g., 1.0): pytorch-lightning==1.5.9, torchmetrics==0.7.0
- OS (e.g., Linux): Linux
- How you installed PyTorch (`conda`, `pip`, source): pip
- Python version: Python 3.9.4
- CUDA/cuDNN version: CUDA Version: 11.4
- GPU models and configuration: 8 GPUs
- Any other relevant information: EC2 instance

### Additional context

This only hangs on the retrieval metrics. When I used classification metrics, things work as expected.
After some digging, it appears to hang on [this line](https://github.com/PyTorchLightning/metrics/blob/1663629e78ff6656f3996010bd04c07ddfc49715/torchmetrics/utilities/data.py#L166) during the call to `compute()`. It's not clear to me why this metric would hang and others not.

**Comment by SkafteNicki** [comment] 2022-01-31 11:37
Hi @riklopfer,
When trying to run your code I indeed also gets the error. However, I also get the following warning:
```
/home/nsde/metrics/torchmetrics/utilities/prints.py:36: 
UserWarning: The ``compute`` method of metric RetrievalPrecision was called before 
the ``update`` method which may lead to errors, as metric states have not yet been updated.
```
indicating that the retrieval precision metric is probably not behaving well due to it not being updated before you try to compute.

**Comment by riklopfer** [comment] 2022-01-31 15:37
@SkafteNicki any suggestions on how to avoid this?

**Comment by SkafteNicki** [comment] 2022-01-31 16:12
@riklopfer Initialize the trainer with `num_sanity_val_steps=0`
```python
trainer = Trainer(
        default_root_dir=os.getcwd(),
        max_epochs=2,
        gpus=args.gpus,
        strategy=DDPPlugin(find_unused_parameters=False),
        num_sanity_val_steps=0
    )
```
problem is that doing the sanity checking the default is to check 2 batches. It is very likely that both batches end up updating `self.val_metrics_other` and not one for `self.val_metrics_other` and one for `self.val_metrics`, thus the latter end up having its metric state not updated before compute is called (at the end of the sanity checking).
Alternatively, you can also increase to some number that makes it more likely that both metrics are getting updated during the sanity checking.

Closing the issue as this is not really a not bug but just related to a corner case of integration with lightning.

**Comment by riklopfer** [comment] 2022-01-31 16:32
@SkafteNicki you successfully debugged the BoringModel but my problem still exists. See the description -- the metric **hangs** in DDP mode -- does not raise and exception. I am struggling to reproduce the issue with minimal code. 

Any idea why this metric would be hanging? Is there a way I can get more verbose output so I might see where it's hanging? Maybe there is a way that I can avoid having validation metric computation distributed?

**Comment by riklopfer** [comment] 2022-01-31 16:36
Unfortunately, it's confidential.

**Comment by SkafteNicki** [comment] 2022-01-31 17:59
Okay in general if a metrics hang it nearly always has to do with unequal workload between the different devices. If you directly had 
```python
if self.global_rank == 0:
    # do something with metric
```
then that is a near guarantee that it will hang. As I understand it, your code has an if-else statement and it is very likely that will lead to unequal workload.

For debugging, I am often doing the most stupid thing you can do: just print stuff. Printing shapes of list/tensors can help identify if one process was assigned more data than some other processes.

**Comment by riklopfer** [comment] 2022-01-31 18:42
> For debugging, I am often doing the most stupid thing you can do: just print stuff.

Yeah. That's what I've been doing on this branch https://github.com/riklopfer/metrics/tree/retrieval-metrics-hang

The last message I see is from here: https://github.com/riklopfer/metrics/blob/93d639c6a022ca1cc7c6125ef1251ea13ee282ab/torchmetrics/utilities/distributed.py#L111

```
gather_all_tensors::result.shape=torch.Size([9])
```

**Comment by SkafteNicki** [comment] 2022-01-31 19:31
Does it print multiple times? One for each process?

I am confident that it is this specific line where it hangs:
https://github.com/riklopfer/metrics/blob/93d639c6a022ca1cc7c6125ef1251ea13ee282ab/torchmetrics/utilities/distributed.py#L119
One process must be waiting for some other process at this point which they for some reason will never get to

**Comment by riklopfer** [comment] 2022-01-31 20:27
> Does it print multiple times? One for each process?

Yes. 

> One process must be waiting for some other process at this point which they for some reason will never get to

That makes sense. It's just unclear to me why it's happening or how I can resolve it. As I mentioned at the top, this only seems to happen for the Retrieval metrics, so if I do the same thing and only compute e.g. F1Score, everything is fine. This indicates that there is something different in the RetrievalMetric that is causing the hang.

**Comment by riklopfer** [comment] 2022-01-31 21:30
https://github.com/pytorch/pytorch/pull/54159

Could this be the root cause of my issue?

**Comment by SkafteNicki** [comment] 2022-02-01 07:58
Not sure about that. Does not seem to be the problem to me.
I core difference between RetrievalPrecision and F1Score is in their states. In retrieval metrics the states are lists:
https://github.com/PyTorchLightning/metrics/blob/408cabed8120033dc6a904fa67902572dabe3ce7/torchmetrics/retrieval/base.py#L107-L109
whereas in most classification metrics they are tensors:
https://github.com/PyTorchLightning/metrics/blob/408cabed8120033dc6a904fa67902572dabe3ce7/torchmetrics/classification/stat_scores.py#L190-L191
This can explain the difference. For F1Score, even if one only one process receives some input the metric would still have an state of equal shape on all ranks since we just add to the metric state in this case. For the RetrievalPrecision metric if only one process receives data it will be appended to the metric state of that process, leading to a difference in shape of the states between the different ranks.

However, this does not mean that there is a problem with the metric and the problem is (still) most likely that the Retrieval metric at some point receive data on one process but not another.

I am sorry that I cannot be any more helpful when the issue is hard to reproduce with a minimal example :]

**Comment by riklopfer** [comment] 2022-02-01 15:18
My use case is that I am training a semi-supervised model where I would like to see validation metrics for examples with observed labels and unobserved. The `rng.random() < 0.2` in BoringModel is a stand-in for `not has_supervision()`. 

I am getting the impression that the way I have implemented this is not really supported. If that's the case, is there a preferred way to implement this? One idea is to create separate datasets at runtime and process them separately during validation, each contributing to a different set of metrics; not sure how to do this though.

**Comment by SkafteNicki** [comment] 2022-02-11 12:38
@riklopfer I think we have come to the agreement that the `RetrievalPrecision` metric does not seem to be the main problem here and I am therefore going to close the issue.
For your particular application I would recommend that you split your data into separate datasets, one supervised and one unsupervised, and process them with individual metrics.

**Closed by SkafteNicki** 2022-02-11 12:38 UTC
Labels: bug / fix, help wanted
